baseURL = "http://example.org/"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "My New Hugo Site"

# language code
languageCode = "en"
# language name
languageName = "English"

# Author config
[author]
  name = "Hannah Busshoff"
  email = "hannah.busshoff@unisg.ch"
  link = ""

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = "posts"
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Teaching"
    url = "/teaching/"
    title = "teaching"
  [[menu.main]]
      weight = 3
      identifier = "cv"
      pre = ""
      post = ""
      name = "CV"
      url = "/cv/"
      title = "cv"
  [[menu.main]]
          weight = 4
          identifier = "Projects"
          pre = ""
          post = ""
          name = "Projects"
          url = "/projects/"
          title = "projects"
# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
